/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfas;

/**
 *
 * @author jefe
 */
public class LoginU extends javax.swing.JFrame {

    /**
     * Creates new form LoginU
     */
    public LoginU() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpLogin = new javax.swing.JPanel();
        jbMesero = new javax.swing.JButton();
        jbIngresar = new javax.swing.JButton();
        jbAdministrador = new javax.swing.JButton();
        jTextpassword = new javax.swing.JTextField();
        jTextUsername = new javax.swing.JTextField();
        jlPassword = new javax.swing.JLabel();
        jlUsername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbMesero.setText("Mesero");
        jbMesero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMeseroActionPerformed(evt);
            }
        });
        jpLogin.add(jbMesero, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, 200, 60));

        jbIngresar.setText("Ingresar seccion");
        jpLogin.add(jbIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 200, 60));

        jbAdministrador.setText("Administrador");
        jpLogin.add(jbAdministrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, 200, 60));

        jTextpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextpasswordActionPerformed(evt);
            }
        });
        jpLogin.add(jTextpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 670, 50));

        jTextUsername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUsernameActionPerformed(evt);
            }
        });
        jpLogin.add(jTextUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 670, 50));

        jlPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon/lock-closed-sharp.png"))); // NOI18N
        jlPassword.setText("Contraseña");
        jpLogin.add(jlPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));

        jlUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon/person-circle.png"))); // NOI18N
        jlUsername.setText("Ingrese su usuario");
        jpLogin.add(jlUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel1.setText("jLabel1");
        jpLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        jPanel1.add(jpLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 320, 850, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 2015, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMeseroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbMeseroActionPerformed

    private void jTextpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextpasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextpasswordActionPerformed

    private void jTextUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUsernameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextUsername;
    private javax.swing.JTextField jTextpassword;
    private javax.swing.JButton jbAdministrador;
    private javax.swing.JButton jbIngresar;
    private javax.swing.JButton jbMesero;
    private javax.swing.JLabel jlPassword;
    private javax.swing.JLabel jlUsername;
    private javax.swing.JPanel jpLogin;
    // End of variables declaration//GEN-END:variables
}
